"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import { Float, OrbitControls, Stars } from "@react-three/drei";
import { useRef, useState } from "react";
import type { Group } from "three";

function Core(){const group=useRef<Group>(null);const [active,setActive]=useState(false);useFrame((state,delta)=>{if(group.current){group.current.rotation.y+=delta*(active?.85:.22);group.current.rotation.x=Math.sin(state.clock.elapsedTime*.45)*.12}});return <group ref={group} onClick={()=>setActive(!active)} scale={active?1.14:1}><mesh><boxGeometry args={[2.65,.32,1.65]}/><meshStandardMaterial color="#071826" metalness={.9} roughness={.2}/></mesh><mesh position={[0,.25,0]}><boxGeometry args={[1.7,.12,.9]}/><meshStandardMaterial color="#1ce1ff" emissive="#0075a3" emissiveIntensity={1.6} metalness={.8}/></mesh><mesh position={[0,.38,0]}><boxGeometry args={[.7,.1,.42]}/><meshStandardMaterial color="#dfff32" emissive="#8dbc00" emissiveIntensity={2}/></mesh>{[[-1.05,0,.55],[1.05,0,.55],[-1.05,0,-.55],[1.05,0,-.55]].map((p,i)=><mesh key={i} position={p as [number,number,number]}><cylinderGeometry args={[.08,.08,.34,20]}/><meshStandardMaterial color="#a5f7ff" emissive="#159abd" emissiveIntensity={1}/></mesh>)}</group>}
function Rings(){const ref=useRef<Group>(null);useFrame((_,d)=>{if(ref.current)ref.current.rotation.z+=d*.28});return <group ref={ref}>{[1.95,2.35].map((r,i)=><mesh key={r} rotation={[Math.PI/2,i*.5,0]}><torusGeometry args={[r,.012,12,120]}/><meshBasicMaterial color={i?"#dfff32":"#35d9ff"}/></mesh>)}</group>}
export default function HardwareCore(){return <div className="hardware-core" aria-label="Interactive 3D hardware core. Drag to inspect and click to energise."><Canvas camera={{position:[0,1.1,5.5],fov:42}} dpr={[1,1.7]}><color attach="background" args={["#06101b"]}/><fog attach="fog" args={["#06101b",5,13]}/><ambientLight intensity={.6}/><pointLight color="#35d9ff" intensity={18} position={[3,3,3]}/><pointLight color="#dfff32" intensity={9} position={[-3,1,-2]}/><Stars radius={14} depth={30} count={500} factor={2} saturation={0}/><Float speed={2} rotationIntensity={.18} floatIntensity={.45}><Core/></Float><Rings/><OrbitControls enablePan={false} minDistance={4} maxDistance={7} autoRotate autoRotateSpeed={.4}/></Canvas><span>3D CORE // DRAG TO INSPECT · CLICK TO ENERGISE</span></div>}
